spring:
  application:
    name: showlist
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: CLIENT_ID
            client-secret: CLIENT_SECRET
            scope: openid, profile, email

  datasource:
    url: jdbc:h2:file:./data/showlist
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true